// RUN: { ptoas %S/reduction_broadcast_family_static.pto --enable-op-fusion --op-lib-dir=%S/../../oplib/level3 --pto-arch=a5 --print-ir-after-all -o /dev/null 2>&1 || true; } | FileCheck %s --check-prefix=STATIC
// RUN: { ptoas %S/reduction_broadcast_family_dynamic_vshape.pto --enable-op-fusion --op-lib-dir=%S/../../oplib/level3 --pto-arch=a5 --print-ir-after-all -o /dev/null 2>&1 || true; } | FileCheck %s --check-prefix=DYNAMIC
// XFAIL: *

// STATIC-LABEL: IR Dump After PTOInstantiateAndLowerToLibCall
// STATIC-DAG: pto.oplib.instance.op = "trowsum"
// STATIC-DAG: pto.oplib.instance.variant_id = "linear"
// STATIC-DAG: pto.oplib.instance.op = "trowmax"
// STATIC-DAG: pto.oplib.instance.variant_id = "linear"
// STATIC-DAG: pto.oplib.instance.op = "trowmin"
// STATIC-DAG: pto.oplib.instance.variant_id = "linear"
// STATIC-DAG: pto.oplib.instance.op = "tcolsum"
// STATIC-DAG: pto.oplib.instance.variant_id = "linear"
// STATIC-DAG: pto.oplib.instance.op = "tcolmax"
// STATIC-DAG: pto.oplib.instance.variant_id = "linear"
// STATIC-DAG: pto.oplib.instance.op = "tcolmin"
// STATIC-DAG: pto.oplib.instance.variant_id = "linear"
// STATIC-DAG: pto.oplib.instance.op = "trowexpand"
// STATIC-DAG: pto.oplib.instance.variant_id = "linear"
// STATIC-DAG: pto.oplib.instance.op = "tcolexpand"
// STATIC-DAG: pto.oplib.instance.variant_id = "linear"
// STATIC-DAG: pto.oplib.instance.op = "trowexpandmul"
// STATIC-DAG: pto.oplib.instance.variant_id = "linear"
// STATIC-DAG: pto.oplib.instance.op = "trowexpanddiv"
// STATIC-DAG: pto.oplib.instance.variant_id = "linear"
// STATIC-DAG: pto.oplib.instance.op = "trowexpandsub"
// STATIC-DAG: pto.oplib.instance.variant_id = "linear"
// STATIC-DAG: pto.oplib.instance.op = "texpands"
// STATIC-DAG: pto.oplib.instance.variant_id = "scalar"
// DYNAMIC-LABEL: IR Dump After PTOInstantiateAndLowerToLibCall
// DYNAMIC-DAG: pto.oplib.instance.op = "trowsum"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "linear"
// DYNAMIC-DAG: pto.oplib.instance.op = "trowmax"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "linear"
// DYNAMIC-DAG: pto.oplib.instance.op = "trowmin"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "linear"
// DYNAMIC-DAG: pto.oplib.instance.op = "tcolsum"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "linear"
// DYNAMIC-DAG: pto.oplib.instance.op = "tcolmax"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "linear"
// DYNAMIC-DAG: pto.oplib.instance.op = "tcolmin"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "linear"
// DYNAMIC-DAG: pto.oplib.instance.op = "trowexpand"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "linear"
// DYNAMIC-DAG: pto.oplib.instance.op = "tcolexpand"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "linear"
// DYNAMIC-DAG: pto.oplib.instance.op = "trowexpandmul"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "linear"
// DYNAMIC-DAG: pto.oplib.instance.op = "trowexpanddiv"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "linear"
// DYNAMIC-DAG: pto.oplib.instance.op = "trowexpandsub"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "linear"
// DYNAMIC-DAG: pto.oplib.instance.op = "texpands"
// DYNAMIC-DAG: pto.oplib.instance.variant_id = "scalar"
