#include "PTO/IR/PTO.h"
#include "PTO/Transforms/Passes.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SCF/Utils/Utils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Pass/Pass.h"

#include "llvm/ADT/SmallVector.h"

namespace mlir {
namespace pto {
#define GEN_PASS_DEF_PTOPOSTFUSIONLOOPUNROLL
#include "PTO/Transforms/Passes.h.inc"
} // namespace pto
} // namespace mlir

using namespace mlir;

namespace {

struct LoopCostModelInputs {
  unsigned bodyOpCount = 0;
  unsigned loopCarriedValueCount = 0;
  unsigned liveValueScore = 0;
  unsigned registerPressureScore = 0;
  unsigned selectedFactor = 1;
  std::optional<int64_t> constantTripCount;
};

static bool isSupportedLeafBodyOp(Operation *op) {
  if (!op || op->hasTrait<OpTrait::IsTerminator>())
    return false;
  if (op->getNumRegions() != 0)
    return false;
  return true;
}

static bool isCandidateLeafCarrierLoop(scf::ForOp loop) {
  if (!loop || !loop->getParentOfType<pto::FusionRegionOp>())
    return false;
  if (!loop->getParentOfType<pto::VecScopeOp>() &&
      !loop->getParentOfType<pto::StrictVecScopeOp>())
    return false;

  for (Operation &op : loop.getBody()->without_terminator()) {
    if (!isSupportedLeafBodyOp(&op))
      return false;
  }
  return true;
}

static unsigned countBodyOps(scf::ForOp loop) {
  unsigned count = 0;
  for (Operation &op : loop.getBody()->without_terminator()) {
    if (isSupportedLeafBodyOp(&op))
      ++count;
  }
  return count;
}

static unsigned estimateLiveValueScore(scf::ForOp loop) {
  unsigned score = loop.getNumRegionIterArgs();
  for (Operation &op : loop.getBody()->without_terminator()) {
    score += op.getNumResults();
    if (!isMemoryEffectFree(&op))
      ++score;
  }
  return score;
}

static std::optional<int64_t> getConstantTripCount(scf::ForOp loop) {
  std::optional<int64_t> lb = getConstantIntValue(loop.getLowerBound());
  std::optional<int64_t> ub = getConstantIntValue(loop.getUpperBound());
  std::optional<int64_t> step = getConstantIntValue(loop.getStep());
  if (!lb || !ub || !step || *step <= 0 || *ub < *lb)
    return std::nullopt;
  return constantTripCount(loop.getLowerBound(), loop.getUpperBound(),
                           loop.getStep());
}

static bool hasAcceptableTailCost(int64_t tripCount, unsigned factor) {
  if (tripCount < static_cast<int64_t>(factor))
    return false;
  int64_t tailTripCount = tripCount % static_cast<int64_t>(factor);
  if (tailTripCount == 0)
    return true;
  // Stay conservative in v1: if more than 25% of iterations would fall into
  // the epilogue, skip this factor and let task group 4 handle richer tails.
  return tailTripCount * 4 <= tripCount;
}

static bool isDynamicPartialUnrollCandidate(scf::ForOp loop,
                                            const LoopCostModelInputs &inputs) {
  if (inputs.constantTripCount)
    return false;

  std::optional<int64_t> lb = getConstantIntValue(loop.getLowerBound());
  std::optional<int64_t> step = getConstantIntValue(loop.getStep());
  if (!lb || !step || *step <= 0)
    return false;

  // Keep the first dynamic-shape revision conservative: only allow x2 partial
  // unroll on short leaf loops with very small loop-carried state. The
  // explicit tail semantics come from SCF's epilogue loop generated by
  // loopUnrollByFactor.
  if (inputs.bodyOpCount == 0 || inputs.bodyOpCount > 8)
    return false;
  if (inputs.loopCarriedValueCount > 1)
    return false;
  if (inputs.registerPressureScore * 2 > 24)
    return false;
  return true;
}

static unsigned chooseUnrollFactorForLoop(scf::ForOp loop,
                                          LoopCostModelInputs &inputs) {
  inputs.bodyOpCount = countBodyOps(loop);
  inputs.loopCarriedValueCount = loop.getNumRegionIterArgs();
  inputs.liveValueScore = estimateLiveValueScore(loop);
  inputs.registerPressureScore =
      inputs.liveValueScore + inputs.loopCarriedValueCount;
  inputs.constantTripCount = getConstantTripCount(loop);

  if (inputs.bodyOpCount == 0 || inputs.bodyOpCount > 12)
    return 1;
  if (!inputs.constantTripCount) {
    if (isDynamicPartialUnrollCandidate(loop, inputs)) {
      inputs.selectedFactor = 2;
      return 2;
    }
    return 1;
  }
  if (*inputs.constantTripCount < 2)
    return 1;
  if (inputs.loopCarriedValueCount > 2)
    return 1;

  for (unsigned factor : {4u, 2u}) {
    if (*inputs.constantTripCount < static_cast<int64_t>(factor))
      continue;
    if (!hasAcceptableTailCost(*inputs.constantTripCount, factor))
      continue;
    if (inputs.bodyOpCount * factor > 24)
      continue;
    if (inputs.registerPressureScore * factor > 32)
      continue;
    inputs.selectedFactor = factor;
    return factor;
  }

  return 1;
}

static FailureOr<unsigned> resolveRequestedUnrollFactor(unsigned requestedFactor,
                                                        func::FuncOp func) {
  if (requestedFactor == 0)
    return 0u;
  if (requestedFactor == 2 || requestedFactor == 4)
    return requestedFactor;

  func.emitError()
      << "unsupported forced-unroll-factor=" << requestedFactor
      << "; expected 0 (auto), 2, or 4";
  return failure();
}

static SmallVector<scf::ForOp, 8>
collectCandidateLeafCarrierLoops(pto::FusionRegionOp fusionRegion) {
  SmallVector<scf::ForOp, 8> loops;
  fusionRegion.walk([&](scf::ForOp loop) {
    if (isCandidateLeafCarrierLoop(loop))
      loops.push_back(loop);
  });
  return loops;
}

struct PTOPostFusionLoopUnrollPass
    : public pto::impl::PTOPostFusionLoopUnrollBase<
          PTOPostFusionLoopUnrollPass> {
  using pto::impl::PTOPostFusionLoopUnrollBase<
      PTOPostFusionLoopUnrollPass>::PTOPostFusionLoopUnrollBase;

  void runOnOperation() override {
    func::FuncOp func = getOperation();
    if (func.isExternal())
      return;

    FailureOr<unsigned> requestedFactorOr =
        resolveRequestedUnrollFactor(forcedUnrollFactor, func);
    if (failed(requestedFactorOr)) {
      signalPassFailure();
      return;
    }
    unsigned requestedFactor = *requestedFactorOr;

    SmallVector<pto::FusionRegionOp, 8> fusionRegions;
    func.walk([&](pto::FusionRegionOp fusionRegion) {
      fusionRegions.push_back(fusionRegion);
    });

    for (pto::FusionRegionOp fusionRegion : fusionRegions) {
      SmallVector<scf::ForOp, 8> candidateLoops =
          collectCandidateLeafCarrierLoops(fusionRegion);
      for (scf::ForOp loop : candidateLoops) {
        LoopCostModelInputs inputs;
        unsigned factor = requestedFactor ? requestedFactor
                                         : chooseUnrollFactorForLoop(loop, inputs);
        if (factor <= 1)
          continue;
        // Only rewrite the carrier loop structure in place. This intentionally
        // leaves pto.yield / fusion-region results untouched and does not
        // materialize any new fusion-local store/load traffic beyond the loop
        // body's existing operations.
        if (failed(loopUnrollByFactor(loop, factor))) {
          signalPassFailure();
          return;
        }
      }
    }
  }
};

} // namespace

std::unique_ptr<Pass> mlir::pto::createPTOPostFusionLoopUnrollPass() {
  return std::make_unique<PTOPostFusionLoopUnrollPass>();
}

std::unique_ptr<Pass> mlir::pto::createPTOPostFusionLoopUnrollPass(
    const pto::PTOPostFusionLoopUnrollOptions &options) {
  return std::make_unique<PTOPostFusionLoopUnrollPass>(options);
}
